// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiaFhbmlYucMzLQX0zB8LaipXBa4_fgvE',
    appId: '1:821350898990:web:ca6fc3aadd0f1a61136ebf',
    messagingSenderId: '821350898990',
    projectId: 'chat-4c460',
    authDomain: 'chat-4c460.firebaseapp.com',
    storageBucket: 'chat-4c460.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwXP623EOFDY4dM2no2NEBWN84XcoaDuU',
    appId: '1:821350898990:android:e722cae22ea7eeca136ebf',
    messagingSenderId: '821350898990',
    projectId: 'chat-4c460',
    storageBucket: 'chat-4c460.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB049IUMHFCFHiiGJMAV1L7E7Dx2fxrprw',
    appId: '1:821350898990:ios:d96061d4a860517d136ebf',
    messagingSenderId: '821350898990',
    projectId: 'chat-4c460',
    storageBucket: 'chat-4c460.appspot.com',
    iosClientId: '821350898990-b64328bn04bo565spmot66vbpabs8ia8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappFirebase',
  );
}
